name: delern_flutter
description: Spaced repetition learning system (Flutter version)

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

dependencies:
  device_info:
  package_info:
  url_launcher:
  flutter_markdown:
  http:
  share:
  shared_preferences:
  quiver:
  built_collection:
  built_value:
  rxdart:
  uuid:
  device_preview:
  flutter_local_notifications:
  provider:
  intl:
  auto_size_text:

  flutter_sentry:
  # Needed for the User context type, version is bound by flutter_sentry.
  sentry:

  amplitude_flutter:

  image_picker:
  cached_network_image:
  app_settings:
  firebase_core:
  firebase_auth:
  firebase_analytics:
  firebase_database:
  firebase_messaging:
  firebase_remote_config:
  firebase_storage:
  firebase_performance:

  google_sign_in:
  flutter_facebook_login:
  sign_in_with_apple:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  intl_translation:
  mockito:
  pedantic:
  built_value_generator:
  test:

  # https://github.com/flutter/flutter/issues/62240.
  build_runner: ^1.10.1

dependency_overrides:
# Uncomment the following to override any dependency.
#  flutter_sentry:
#    path: ../../flutter_sentry/

flutter:
  uses-material-design: true

  assets:
    - images/
